// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAT1DJ5_TBD0R9oFANyVJbV75arhqjpOw',
    appId: '1:1027012576093:web:38ded834ee5105d3f01eb4',
    messagingSenderId: '1027012576093',
    projectId: 'tmdt-bangiay',
    authDomain: 'tmdt-bangiay.firebaseapp.com',
    databaseURL: 'https://tmdt-bangiay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdt-bangiay.appspot.com',
    measurementId: 'G-JNGSQPY96S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmR44TbGEKahswFmh2GGlZ0y8fGwSEvKI',
    appId: '1:1027012576093:android:0a323bf26736a1aef01eb4',
    messagingSenderId: '1027012576093',
    projectId: 'tmdt-bangiay',
    databaseURL: 'https://tmdt-bangiay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdt-bangiay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb-ZhRDkRMfy5PtxxC6MsWu7eawShUJLk',
    appId: '1:1027012576093:ios:1b8f9a0aa5f8fa0df01eb4',
    messagingSenderId: '1027012576093',
    projectId: 'tmdt-bangiay',
    databaseURL: 'https://tmdt-bangiay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdt-bangiay.appspot.com',
    iosBundleId: 'com.example.doanTmdt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb-ZhRDkRMfy5PtxxC6MsWu7eawShUJLk',
    appId: '1:1027012576093:ios:4b1446e9fdb72ea1f01eb4',
    messagingSenderId: '1027012576093',
    projectId: 'tmdt-bangiay',
    databaseURL: 'https://tmdt-bangiay-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tmdt-bangiay.appspot.com',
    iosBundleId: 'com.example.doanTmdt.RunnerTests',
  );
}
